name: Sample Github Actions Workflow
on:
  push:
    branches:
    - main
jobs:
  file-generation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Show current files in the repository
      run: ls -l
      
    - name: generate files
      run: bash ./file_generator.sh

    - name: Commit and push generated files
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: file_*.txt

  list-files:
    runs-on: ubuntu-latest
    needs: file-generation
    steps:
    - name: Download generated files
      uses: actions/download-artifact@v4
      with:
        name: generated-files

    - name: List generated files
      run: ls -l file_*.txt