name: Sample Github Actions Workflow
on:
  push:
    branches:
    - main
jobs:
  file-generation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: generate files
      run: bash ./file_generator.sh

    - name: Commit and push generated files
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: file_*.txt

  